#!/usr/bin/env ruby
require 'rubygems'
require 'fileutils'

if not ARGV[0]
  puts "Install directory must be provided"
  exit
end

install_directory = Dir.new(ARGV[0])
plugin_dir = Dir.getwd
path = '/lib/active_merchant/billing/gateways/'

FileUtils.mkdir_p install_directory.path + path if not File.directory? install_directory.path + path
FileUtils.cp_r ["#{plugin_dir}#{path}paypal_adaptive_payments.rb", "#{plugin_dir}#{path}paypal_adaptive_payments/"], install_directory.path + path